
FILE_NAME=logicop

compile:
	g++ -fdiagnostics-color=always -g $(FILE_NAME).cpp  -o $(FILE_NAME)

execute:
	./$(FILE_NAME)


cne:
	g++ -fdiagnostics-color=always -g $(FILE_NAME).cpp  -o $(FILE_NAME) && ./$(FILE_NAME)

rmbin:
	rm $(FILE_NAME)